Test/#61 user module tests fixing
SathMenthu/megak-headhunter-backend pull request #18
Opened 2022-07-26 19:57 UTC by Dzejkop02

User module tests fixed.

2022-07-27 07:00 UTC, SathMenthu approved these changes

2022-07-28 11:16 UTC, adamDmrk approved these changes

2022-07-29 09:06 UTC, iwomipl requested changes
Damn, guys. Again sorry, for inconveinence. Kuba needs still to change some parts.
user.controller.spec.ts You have to get user variable in lines 37 and 56 to work with FilteredUser Interface.
user.service.interface.spec.ts we have a problem with TS, there is no RolesEnum it's RoleEnum, furthermore tere is (possibly) connected problem with testUserObj which is not good for function in line 73. And might also be the case on line 79.

2022-07-29 15:18 UTC, SathMenthu approved these changes

2022-07-30 16:29 UTC, iwomipl approved these changes
Works fine for me. Great!

2022-07-30 16:35 UTC, merged